// Code generated by baton-sdk. DO NOT EDIT!!!
package config

import "reflect"

type AzureInfrastructure struct {
	UseCliCredentials                     bool   `mapstructure:"use-cli-credentials"`
	AzureClientSecret                     string `mapstructure:"azure-client-secret"`
	AzureTenantId                         string `mapstructure:"azure-tenant-id"`
	AzureClientId                         string `mapstructure:"azure-client-id"`
	Mailboxsettings                       bool   `mapstructure:"mailboxSettings"`
	SkipAdGroups                          bool   `mapstructure:"skip-ad-groups"`
	GraphDomain                           string `mapstructure:"graph-domain"`
	SkipUnusedRoles                       bool   `mapstructure:"skip-unused-roles"`
	SkipSyncStorageContainers             bool   `mapstructure:"skip-sync-storage-containers"`
	EnableSyncExternalResourcesViaBatonId bool   `mapstructure:"enable-sync-external-resources-via-baton-id"`
	SkipEntraIdP2LicenseFeatures          bool   `mapstructure:"skip-entra-id-p2-license-features"`
}

func (c *AzureInfrastructure) findFieldByTag(tagValue string) (any, bool) {
	v := reflect.ValueOf(c).Elem() // Dereference pointer to struct
	t := v.Type()

	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)
		tag := field.Tag.Get("mapstructure")

		if tag == tagValue {
			return v.Field(i).Interface(), true
		}
	}
	return nil, false
}

func (c *AzureInfrastructure) GetStringSlice(fieldName string) []string {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return []string{}
	}
	t, ok := v.([]string)
	if !ok {
		panic("wrong type")
	}
	return t
}

func (c *AzureInfrastructure) GetString(fieldName string) string {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return ""
	}
	if t, ok := v.(string); ok {
		return t
	}
	if t, ok := v.([]byte); ok {
		return string(t)
	}
	panic("wrong type")
}

func (c *AzureInfrastructure) GetInt(fieldName string) int {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return 0
	}
	t, ok := v.(int)
	if !ok {
		panic("wrong type")
	}
	return t
}

func (c *AzureInfrastructure) GetBool(fieldName string) bool {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return false
	}
	t, ok := v.(bool)
	if !ok {
		panic("wrong type")
	}
	return t
}

func (c *AzureInfrastructure) GetStringMap(fieldName string) map[string]any {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return map[string]any{}
	}
	t, ok := v.(map[string]any)
	if !ok {
		panic("wrong type")
	}
	return t
}
